---
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devportal
      - POSTGRES_PASSWORD=devportal

volumes:
  postgres:
