"""add component tech stack

Revision ID: f49eb0d3e125
Revises: dda85011ffd6
Create Date: 2024-09-07 21:04:49.599147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f49eb0d3e125"
down_revision: Union[str, None] = "dda85011ffd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "techstack",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("component", sa.Column("techstack_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_component_techstack_id"), "component", ["techstack_id"], unique=False
    )
    op.create_foreign_key(
        "component_techstack_id_fkey",
        "component",
        "techstack",
        ["techstack_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("component_techstack_id_fkey", "component", type_="foreignkey")
    op.drop_index(op.f("ix_component_techstack_id"), table_name="component")
    op.drop_column("component", "techstack_id")
    op.drop_table("techstack")
    # ### end Alembic commands ###
